__default__:
    account: ebf11_c
    time: 48:00:00
    nodes: 1
    ntasks: 8
    mem_per_cpu: 8192
fig2:
    account: ebf11_c
    time: 1:00:00
    nodes: 1
    ntasks: 1
    mem_per_cpu: 8192
fig3:
    account: ebf11_c
    time: 1:00:00
    nodes: 1
    ntasks: 1
    mem_per_cpu: 8192
